name: Build VoidSU

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-manager:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spoofed: [ false ]

    defaults:
      run:
        working-directory: ./manager

    env:
      KEYSTORE_BASE64: ${{ secrets.VOIDSU_KEYSTORE_B64 }}
      KEYSTORE_PASSWORD: ${{ secrets.VOIDSU_KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.VOIDSU_KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.VOIDSU_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Keystore
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        run: |
          echo "Setting up keystore from GitHub Secrets..."
          echo "$KEYSTORE_BASE64" | base64 -d > key.jks
          {
            echo "KEYSTORE_FILE=key.jks"
            echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD"
            echo "KEY_ALIAS=$KEY_ALIAS"
            echo "KEY_PASSWORD=$KEY_PASSWORD"
          } >> gradle.properties

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Build with Gradle
        run: ./gradlew assembleRelease --build-cache

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoidSU-Manager
          path: manager/app/build/outputs/apk/release/*.apk

      - name: Upload mappings
        uses: actions/upload-artifact@v4
        with:
          name: VoidSU-Mappings
          path: "manager/app/build/outputs/mapping/release/"
